// ─────────────────────────────────────────────────────────────────────────────
// ui/src/views/timeline/timelineTypes.ts
//
// TypeScript types for the refactored timeline system.
//
// The timeline is a PROJECTION layer — events derive from other modules.
// No authoritative data lives here.
// ─────────────────────────────────────────────────────────────────────────────

import type { FantasyDate } from './calendarUtils';

// ── Timeline Event ────────────────────────────────────────────────────────────

export type TimelineEventCategory =
  | 'quest'
  | 'war'
  | 'npc'
  | 'travel'
  | 'session'
  | 'faction'
  | 'political'
  | 'battle'
  | 'discovery'
  | 'natural'
  | 'social'
  | 'mystery'
  | 'other';

export interface TimelineDependency {
  type: 'after' | 'before';
  eventId: string;
  offsetDays?: number;
}

export interface TimelineEvent {
  id: string;
  title: string;
  description?: string;

  // Temporal position
  startDate: FantasyDate;
  endDate?: FantasyDate;

  // Classification
  lane: TimelineLaneId;
  category: TimelineEventCategory;

  // Source linking (this event is derived from another module's data)
  sourceType?: string;  // 'campaign_events', 'quests', 'sessions', etc.
  sourceId?: string;    // ID in the source table
  autogenerated?: boolean;

  // Dependency graph (future expansion)
  dependencies?: TimelineDependency[];

  // Presentation
  tags?: string[];
  icon?: string;
  color?: string;

  // GM visibility control
  isPlayerFacing: boolean;
  significance: 'trivial' | 'minor' | 'moderate' | 'major' | 'critical';
}

// ── Lanes / Tracks ────────────────────────────────────────────────────────────

export type TimelineLaneId =
  | 'main-story'
  | 'party'
  | 'factions'
  | 'wars'
  | 'divine'
  | 'character-arcs'
  | 'cosmic'
  | 'world'
  | 'other';

export interface TimelineLane {
  id: TimelineLaneId;
  label: string;
  icon: string;
  color: string;
  collapsed: boolean;
  visible: boolean;
  order: number;
}

// ── Zoom / Scale ──────────────────────────────────────────────────────────────

export type ZoomLevel = 'era' | 'year' | 'month' | 'week' | 'day';

export interface ZoomConfig {
  level: ZoomLevel;
  pixelsPerDay: number;
  gridLabel: (date: FantasyDate) => string;
  gridSpanDays: number;
}

// ── Timeline State ────────────────────────────────────────────────────────────

export type TimelineMode = 'historical' | 'gm-future' | 'player-safe';

export interface TimelineViewport {
  scrollLeft: number;
  zoomLevel: ZoomLevel;
  centerDate?: FantasyDate;
}

export interface TimelineFilter {
  categories: Set<TimelineEventCategory>;
  lanes: Set<TimelineLaneId>;
  showGmOnly: boolean;
  searchQuery: string;
  significanceMin: TimelineEvent['significance'];
}

// ── Sync Event types (for automatic population) ───────────────────────────────

export interface SyncSource {
  type: 'quest' | 'session' | 'faction' | 'npc' | 'manual';
  id: string;
  name: string;
  date: string | null;
  eventType: string;
  significance: TimelineEvent['significance'];
  isPlayerFacing: boolean;
  description?: string;
}
